---
name: Build Tandem
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  tandem-binary:
    runs-on: ubuntu-latest
    container: python:3.11-bookworm
    steps:
      - uses: actions/checkout@v5

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build Binary File
        run: pyinstaller update_discord.py --onefile --name tandem

      - name: Publish Binary file as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tandem
          path: dist
